### ISSUE TITLE
News update and TYPO3 11 LTS support

### ISSUE THREAD

**Issue by dennismetz** [BrainAppeal/campus_events_convert2news#2]
Is there an update planned to support news in version >9? 
And TYPO3 11 LTS?

The question also applies to the other extensions like campus_events_connector

**Comment by HeldVomErdbeerfeld** [comment]
Hi,
thanks for the Reminder.

Support for TYPO3 v11 with News v9 will come. 
We can't promie any release date yet but hopefully it will be soon.

Also campus_events_connector is planned to be updated for TYPO3 11.

**Comment by BA-JBI** [comment]
Hi,
thanks for the Reminder.

Support for TYPO3 v11 with News v9 will come.
We can't promie any release date yet but hopefully it will be soon.

Also campus_events_connector is planned to be updated for TYPO3 11.

**Comment by dennismetz** [comment]
Hi,
I saw that you recently released the update for "campus_events_convert2news" and "campus_events_frontend" for 11LTS. 

However, not (yet) in TER and unfortunately not yet the dependency "campus_events_connector" (which is required according to the composer.json) of "campus_events_convert2news".

Is there already an update for this?

**Comment by BA-JBI** [comment]
Hi,

New version with TYPO3 v11 and News v9 support is now released in TER
https://extensions.typo3.org/extension/campus_events_convert2news
